[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
description = "Proteus is intended to make dynamic transformation of data using serde serializable, deserialize using JSON and a JSON transformation syntax similar to Javascript JSON syntax."
edition = "2018"
keywords = [
    "json",
    "transform",
    "transformation",
]
license = "MIT OR Apache-2.0"
name = "proteus"
readme = "README.md"
repository = "https://github.com/rust-playground/proteus"
version = "0.2.0"

[badges.travis-ci]
repository = "rust-playground/proteus"

[[bench]]
harness = false
name = "bench"

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.7"
serde_json = "1.0.53"
typetag = "0.1.4"
thiserror = "1.0.19"

[dependencies.serde]
features = ["derive"]
version = "1.0.110"

[dev-dependencies]
criterion = "0.3.2"

[lib]
bench = false
